version: "0.2"
ignorePaths:
  - archive
  - dist
  - migrations
  - node_modules
dictionaries:
  - en_US
  - softwareTerms
  - bash
  - node
  - npm
  - html
  - css
  - typescript
  - filetypes
words:
  - abortable
  - eventsource
  - filehelper
  - hackai
  - inversify
  - libsql
  - loglevel
  - logtime
  - qrcode
  - scaning
  - wechat
  - wechaty
ignoreWords:
  - trivago
  - zhengxs
