version: "0.2"
ignorePaths:
  - archive
  - dist
  - node_modules
dictionaries:
  - en_US
  - softwareTerms
  - bash
  - node
  - npm
  - html
  - css
  - typescript
  - filetypes
words:
  - aisearch
  - aistudio
  - bduss
  - chatglm
  - claudeai
  - deepl
  - dingtalk
  - douban
  - erniebot
  - glmapi
  - gptapi
  - hotlist
  - hunyuan
  - jiti
  - keyv
  - kimi
  - langchain
  - languagedetect
  - llmapi
  - llms
  - moyu
  - msgtype
  - openai
  - popmart
  - preinstall
  - qian
  - qianwen
  - qiniu
  - tiktoken
  - trivago
  - urllib
  - userid
  - wechat
  - wechaty
  - xinghuo
  - xverse
  - yiyan
  - yiyian
ignoreWords:
  - zhengxs
